# NumPy

* Jake VanderPlas. 2016. *Python Data Science Handbook: Essential Tools for Working with Data*. O'Reilly Media, Inc.
* Chapter 2 - Introduction to NumPy
* https://github.com/jakevdp/PythonDataScienceHandbook

In [2]:
import numpy as np
np.__version__

'1.26.4'

In [3]:
# type TAB to get the HUGE numpy namespace
#np.

## Data Types

NumPy provides an alternative implementation for numerical arrays, improving the performance of data-driven computation compared to standard Python built-in lists.


### Python Integers vs C Integers

* Python `int`s are *complex* objects (written in C)
   * Dynamically-typed language
   * Almost infinite integer arithmetic precision
```c
struct _longobject {
    long ob_refcnt;         # reference count
    PyTypeObject *ob_type;  # type of the variable
    size_t ob_size;         # size of the following data members
    long ob_digit[1];       # integer value encoded into a long array
};
```
* C language integers (char, short, int, long, long...) are simple references to a position in memory whose bytes encode an integer value.

### Python Lists vs NumPy Arrays

* Python `list`s are *complex* objects (much more than `int`s)
   * `list`s are heterogeneous
   * Different object types are different sizes 
   * `list`s contain an array with <u>references</u> to each object
   * Contain a pointer to a block of pointers, each of which points to a Python object
* *Standard* Numpy arrays are homogeneus.
   * Contain a single pointer to one contiguous block of data.

<center><img src="img/array_vs_list.png" alt="NumPy array vs python list" style="width: 100%;"/></center>

## NumPy Arrays

### Creating Arrays from Python Lists

* `np.array(some_list)` &rarr; create an (homogeneous) array
* `np.array(some_list, dtype=<data type>)` &rarr; create an array of a given type

<br>

In [4]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

<br>

In [5]:
np.array([1, 4, 2, 5, 3], dtype='float32')

array([1., 4., 2., 5., 3.], dtype=float32)

<br>
If types do not match, NumPy will upcast if possible:

In [6]:
np.array([1, 4, 2, 5.9, 3])

array([1. , 4. , 2. , 5.9, 3. ])

<br>
Nested lists result in multi-dimensional arrays

In [7]:
np.array([[ 0,  1,  2,  3], [10, 11, 12, 13], [20, 21, 22, 23]])

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

### NumPy Standard Data Types

when constructing an array, the data type (`dtype`) argument can be specified using:
 * string &rarr; `dtype='float32'`
 * NumPy object &rarr; `dtype=np.float32`

<br>

In [8]:
np.array([1, 4, 2, 5, 3], dtype='float32')

array([1., 4., 2., 5., 3.], dtype=float32)

<br>

In [9]:
np.array([1, 4, 2, 5, 3], dtype=np.float32)

array([1., 4., 2., 5., 3.], dtype=float32)

|  Data type | Description                                                                   |   |   |   |
|:----------:|-------------------------------------------------------------------------------|---|---|---|
| bool_      | Boolean (True or False) stored as a byte                                      |   |   |   |
| int_       | Default integer type (same as C long; normally either int64 or int32)         |   |   |   |
| intc       | Identical to C int (normally int32 or int64)                                  |   |   |   |
| intp       | Integer used for indexing (same as C ssize_t; normally either int32 or int64) |   |   |   |
| int8       | Byte (-128 to 127)                                                            |   |   |   |
| int16      | Integer (-32768 to 32767)                                                     |   |   |   |
| int32      | Integer (-2147483648 to 2147483647)                                           |   |   |   |
| int64      | Integer (-9223372036854775808 to 9223372036854775807)                         |   |   |   |
| uint8      | Unsigned integer (0 to 255)                                                   |   |   |   |
| uint16     | Unsigned integer (0 to 65535)                                                 |   |   |   |
| uint32     | Unsigned integer (0 to 4294967295)                                            |   |   |   |
| uint64     | Unsigned integer (0 to 18446744073709551615)                                  |   |   |   |
| float_     | Shorthand for float64.                                                        |   |   |   |
| float16    | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa             |   |   |   |
| float32    | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa           |   |   |   |
| float64    | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa          |   |   |   |
| complex_   | Shorthand for complex128.                                                     |   |   |   |
| complex64  | Complex number, represented by two 32-bit floats                              |   |   |   |
| complex128 | Complex number, represented by two 64-bit floats                              |   |   |   |

### Creating Arrays from Scratch

Default values of `dtype` (most of times):
 * Integers &rarr; `int64`
 * Reals (floating point) &rarr; `float64`

<br>

* `np.zeros(10)` &rarr; a length-10 array filled with zeros 

<br>

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

<br>

In [11]:
np.zeros(10, dtype='int64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

<br>

In [12]:
np.zeros(10, dtype='float32')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

<br>

In [13]:
np.zeros(10, dtype='int32')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

<br>

* `np.eye(3)` &rarr; a 3x3 identity matrix

<br>

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<br>

* `np.ones((3,5))` &rarr; a 3x5 array filled with ones

<br>

In [15]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

<br>

* `np.full((3,5), 1.8)` &rarr; a 3x5 array filled with `1.8`

<br>

In [16]:
np.full((3,5), 1.8)

array([[1.8, 1.8, 1.8, 1.8, 1.8],
       [1.8, 1.8, 1.8, 1.8, 1.8],
       [1.8, 1.8, 1.8, 1.8, 1.8]])

<br>

* `np.empty((3,5))` &rarr; an <u>*uninitialized*</u> 3x5 array

<br>

In [17]:
np.empty((3,5))

array([[1.8, 1.8, 1.8, 1.8, 1.8],
       [1.8, 1.8, 1.8, 1.8, 1.8],
       [1.8, 1.8, 1.8, 1.8, 1.8]])

<br>

* `np.random.random((3,5))` &rarr; a 3x5 array of uniformly distributed random values in the half-open interval $[0,1)$

<br>

In [18]:
np.random.random((3,5))

array([[0.64119947, 0.5205102 , 0.66777645, 0.84419806, 0.61865786],
       [0.91227258, 0.0804815 , 0.73453123, 0.00962788, 0.26980894],
       [0.66882892, 0.34428685, 0.63485121, 0.82953395, 0.83350037]])

<br>

* `np.random.seed(int)` &rarr; sets a seed for random number generation (**provides reproducibility**)


<br>

In [19]:
np.random.seed(43)
np.random.random((3,5))

array([[0.11505457, 0.60906654, 0.13339096, 0.24058962, 0.32713906],
       [0.85913749, 0.66609021, 0.54116221, 0.02901382, 0.7337483 ],
       [0.39495002, 0.80204712, 0.25442113, 0.05688494, 0.86664864]])

<br>

* `np.random.normal(10, 2, (3,5))` &rarr; a 3x5 array of normally distributed random values with $\mu = 10$ and $\sigma = 2$

<br>

In [20]:
np.random.normal(10, 2, (3, 5))

array([[ 9.06239973,  7.247008  ,  8.96229899,  9.54920845, 10.41643253],
       [10.40961276,  9.83619328, 10.67376611,  9.85909104, 11.18066954],
       [ 8.80587096, 10.48544469,  9.38402231, 11.21093121,  7.00980231]])

<br>

* `np.random.randint(-7, 3, (3, 5))` &rarr; a 3x5 array of random integers in the half-open interval $[-7,3)$

<br>

In [21]:
np.random.randint(-7, 3, (3, 5))

array([[-2, -2, -2,  1,  0],
       [-4, -1, -4, -5, -3],
       [-5,  0, -4, -1,  1]])

<br>

* `np.arange(4, 20, 2)` &rarr; an array filled with a linear sequence in the range $[4,20)$ and step $2$

<br>

In [22]:
np.arange(4, 20, 2)

array([ 4,  6,  8, 10, 12, 14, 16, 18])

<br>

* `np.linspace(1, 7, 5)` &rarr; an array of five values evenly spaced in the range $[1,7]$

<br>

In [23]:
np.linspace(1, 7, 5)

array([1. , 2.5, 4. , 5.5, 7. ])

### More on NumPy Arrays

* Array dimensions
* Array attributes
* Array indexing
* Array slicing
* Reshaping of arrays
* Array concatenation and splitting

#### Array dimensions

NumPy arrays can have any number of dimensions:

* 0-dimensional arrays &rarr; **scalars** or **rank-0 tensor**
* 1-dimensional arrays &rarr; **vectors** or **rank-1 tensor**
* 2-dimensional arrays &rarr; **matrices** or **rank-2 tensor**
* 3-dimensional arrays &rarr; **tensors** or **rank-3 tensor**
* ...
* N-dimensional arrays &rarr; **tensors** or **rank-N tensor**


In [24]:
np.random.randint(1,10,(2,2,2,3,6))

array([[[[[4, 7, 8, 5, 6, 4],
          [6, 4, 9, 4, 6, 2],
          [7, 1, 1, 8, 2, 4]],

         [[2, 6, 9, 1, 4, 7],
          [5, 7, 8, 5, 6, 9],
          [5, 8, 5, 3, 7, 8]]],


        [[[9, 9, 2, 9, 6, 6],
          [9, 7, 9, 4, 5, 3],
          [4, 2, 5, 3, 3, 2]],

         [[5, 6, 6, 1, 4, 5],
          [8, 2, 3, 8, 4, 2],
          [2, 4, 7, 6, 9, 1]]]],



       [[[[6, 1, 9, 7, 8, 9],
          [9, 8, 2, 5, 2, 7],
          [4, 1, 2, 8, 9, 4]],

         [[3, 1, 4, 3, 1, 3],
          [7, 8, 5, 5, 7, 1],
          [5, 7, 1, 5, 7, 4]]],


        [[[7, 8, 9, 2, 5, 6],
          [2, 9, 1, 3, 3, 8],
          [7, 6, 1, 5, 1, 9]],

         [[9, 2, 9, 2, 7, 1],
          [3, 2, 6, 1, 6, 6],
          [9, 4, 3, 1, 6, 6]]]]])

#### Array attributes

Given a NumPy array `x`:

* `x.ndim` &rarr; number of dimensions
* `x.shape` &rarr; a tuple of size `x.ndim` containing the size of each dimension
* `x.size` &rarr; total size of the array
* `x.dtype` &rarr; data type of the array

<br>

In [25]:
x = np.random.rand(3, 4)
print(x)
print(f'{x.ndim=}  {x.shape=}  {x.size=}  {x.dtype=}')

[[0.9973726  0.48601552 0.32129159 0.973439  ]
 [0.99871854 0.4452131  0.0447457  0.44706112]
 [0.7101748  0.62607133 0.67064977 0.97191886]]
x.ndim=2  x.shape=(3, 4)  x.size=12  x.dtype=dtype('float64')


#### Array indexing

<br>

One dimensional arrays are indexed as Python lists:

In [26]:
x = np.arange(100,110)
x[3]

103

<br>
Negative indexes are valid as with Python lists:

In [27]:
x[-1],x[-10]

(109, 100)

<br>
Multi-dimensional arrays are indexed with a comma-separated tuple of indices

In [28]:
x = np.random.rand(3,4)
print(x)
print(x[0,3], x[-1,0])

[[0.66197124 0.0914502  0.58973101 0.21158101]
 [0.79507563 0.35030598 0.50243648 0.70353915]
 [0.17162768 0.60105944 0.16003461 0.8265784 ]]
0.21158100640626754 0.17162767591793848


Values can be modified using any of the above index notation.

In [29]:
x = np.arange(10)
print(x)
x[-1] = 20
print(x)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8 20]


<br>
NumPy arrays have fixed types. If you set a float value to an element of an int array, the value is truncated.

In [30]:
print(x)
x[-1] = 17.321
print(x)

[ 0  1  2  3  4  5  6  7  8 20]
[ 0  1  2  3  4  5  6  7  8 17]


#### Array slicing

<br>

NumPy slicing syntax follows that of the standard Python list

* `x[start:stop:step]`
* If omitted, default values apply:
   * `start=0`
   * `stop=size_of_dimension`
   * `step=1`

In [31]:
x = np.arange(10)
print(f'{x[:5]=}')
print(f'{x[5:]=}')
print(f'{x[4:7]=}')
print(f'{x[::2]=}')
print(f'{x[::-1]=}')
print(f'{x[5::-2]=}')

x[:5]=array([0, 1, 2, 3, 4])
x[5:]=array([5, 6, 7, 8, 9])
x[4:7]=array([4, 5, 6])
x[::2]=array([0, 2, 4, 6, 8])
x[::-1]=array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
x[5::-2]=array([5, 3, 1])


In [32]:
x = np.random.rand(3,5)
print(f'{x=}')
print(f'{x[1,:]=}')
print(f'{x[1]=}') # equivalent
print(f'{x[:,1]=}')
print(f'{x[:2,3:]=}')
print(f'{x[0,::-1]=}')
print(f'{x[::-1,1]=}')

x=array([[0.33270163, 0.54669719, 0.8307106 , 0.96906706, 0.32753498],
       [0.08837382, 0.96348912, 0.98930344, 0.91907709, 0.85048569],
       [0.49369274, 0.46861656, 0.55895281, 0.1069022 , 0.89873709]])
x[1,:]=array([0.08837382, 0.96348912, 0.98930344, 0.91907709, 0.85048569])
x[1]=array([0.08837382, 0.96348912, 0.98930344, 0.91907709, 0.85048569])
x[:,1]=array([0.54669719, 0.96348912, 0.46861656])
x[:2,3:]=array([[0.96906706, 0.32753498],
       [0.91907709, 0.85048569]])
x[0,::-1]=array([0.32753498, 0.96906706, 0.8307106 , 0.54669719, 0.33270163])
x[::-1,1]=array([0.46861656, 0.96348912, 0.54669719])


Unlike Python list slices, array slices return **views** rather than copies:

<br>

In [33]:
x = np.random.rand(3,5)
print(f'{x=}')
y = x[1,::2]
print(f'{y=}')
print('-'*40)
y[0] = 0
print(f'{y=}')
print(f'{x=}')

x=array([[0.61514721, 0.99204581, 0.6925764 , 0.35473485, 0.17346336],
       [0.04616806, 0.32678971, 0.35579443, 0.47938721, 0.65897812],
       [0.08594221, 0.29644561, 0.20342314, 0.65215974, 0.57715637]])
y=array([0.04616806, 0.35579443, 0.65897812])
----------------------------------------
y=array([0.        , 0.35579443, 0.65897812])
x=array([[0.61514721, 0.99204581, 0.6925764 , 0.35473485, 0.17346336],
       [0.        , 0.32678971, 0.35579443, 0.47938721, 0.65897812],
       [0.08594221, 0.29644561, 0.20342314, 0.65215974, 0.57715637]])


Explicit copies of arrays or subarrays (slices) can be created: `x.copy()`

<br>

In [34]:
x = np.random.rand(3,5)
print(f'{x=}')
y = x[1,::2].copy()
print(f'{y=}')
print('-'*40)
y[0] = 0
print(f'{y=}')
print(f'{x=}')

x=array([[0.68180214, 0.21692997, 0.02226975, 0.03897417, 0.45671379],
       [0.8776101 , 0.53915719, 0.52549328, 0.54422628, 0.51641898],
       [0.88635236, 0.4101944 , 0.81952181, 0.832217  , 0.59418099]])
y=array([0.8776101 , 0.52549328, 0.51641898])
----------------------------------------
y=array([0.        , 0.52549328, 0.51641898])
x=array([[0.68180214, 0.21692997, 0.02226975, 0.03897417, 0.45671379],
       [0.8776101 , 0.53915719, 0.52549328, 0.54422628, 0.51641898],
       [0.88635236, 0.4101944 , 0.81952181, 0.832217  , 0.59418099]])


#### Reshaping of arrays

* `reshape(a, newshape)` &rarr; a reshaped **view** of an array
* `a.reshape(newshape)` &rarr; a reshaped **view** of an array

<br>

In [38]:
np.reshape(np.arange(10), (2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

<br>

In [39]:
np.arange(10).reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

<br>

In [49]:
a = np.arange(10)
b = a.reshape((2,5))
c = b.reshape((1,10))
b[0,0] = -8
print(f'{a=}\n{b=}\n{c=}')

a=array([-8,  1,  2,  3,  4,  5,  6,  7,  8,  9])
b=array([[-8,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])
c=array([[-8,  1,  2,  3,  4,  5,  6,  7,  8,  9]])


`np.newaxis`, when used in Array slicing adds a new dimension (does a reshape):

<br>

In [95]:
from numpy import newaxis
a = np.arange(4)     # vector
b = a[newaxis,:]  # row vector  a.reshape((1,4))
c = a[:,newaxis]  # column vector a.reshape((4,1))
a[0] = -8
print(f'{a=}\n{b=}\n{c=}')

a=array([-8,  1,  2,  3])
b=array([[-8,  1,  2,  3]])
c=array([[-8],
       [ 1],
       [ 2],
       [ 3]])


#### Array concatenation and splitting

<br>

* Array **concatenation** &rarr; combine multiple arrays into one
   * `np.concatenate` , `np.vstack` and `np.hstack`
* Array **splitting** &rarr; split a single array into multiple arrays
   * `np.split` , `np.vsplit` and `np.hsplit`

* `concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")`
   * `(a1, a2, ...)` &rarr; array sequence
   * `axis` &rarr; the axis along which the arrays will be joined
   * arrays must have the dimension corresponding to `axis`
   * arrays must have the same shape, except in the dimension corresponding to `axis`

<br>

In [130]:
a = np.arange(0,4)
b = np.arange(4,8)
c = np.arange(8,12)
d = np.concatenate((a,b,c))
print(f'{a=}\n{b=}\n{c=}\n{d=}')

a=array([0, 1, 2, 3])
b=array([4, 5, 6, 7])
c=array([ 8,  9, 10, 11])
d=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


<br>

In [131]:
# ERROR: arrays a,b and c does not have dimension 1
#np.concatenate((a,b,c), axis=1)

In [132]:
a2,b2,c2 = a[newaxis,:],b[newaxis,:],c[newaxis,:]
print(f'{a2=}\n{b2=}\n{c2=}')

a2=array([[0, 1, 2, 3]])
b2=array([[4, 5, 6, 7]])
c2=array([[ 8,  9, 10, 11]])


<br>

In [133]:
np.concatenate((a2,b2,c2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

<br>

In [134]:
np.concatenate((a2,b2,c2), axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

<br>

In [135]:
np.concatenate((a2,b2,c2), axis=1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

* `vstack` and `hstack` - 2 (or more) dimensional arrays
    * `vstack((a1, a2, ...))` == `concatenate((a1, a2, ...), axis=0)`
    * `hstack((a1, a2, ...))` == `concatenate((a1, a2, ...), axis=1)`

<br>

In [136]:
a = np.arange(0,8).reshape((2,4))
b = np.arange(8,16).reshape((2,4))
c = np.hstack((a,b))
d = np.concatenate((a,b), axis=1)
e = np.vstack((a,b))
f = np.concatenate((a,b), axis=0)
print(f'{a=}\n{b=}\n{c=}\n{d=}\n{e=}\n{f=}')

a=array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
b=array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])
c=array([[ 0,  1,  2,  3,  8,  9, 10, 11],
       [ 4,  5,  6,  7, 12, 13, 14, 15]])
d=array([[ 0,  1,  2,  3,  8,  9, 10, 11],
       [ 4,  5,  6,  7, 12, 13, 14, 15]])
e=array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])
f=array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])


* `vstack` and `hstack` - 1 dimensional arrays
    * `vstack((a1, a2, ...))` == `concatenate((a1[newaxis,:], a2[newaxis,:], ...))`
    * `hstack((a1, a2, ...))` == `concatenate((a1, a2, ...))`

<br>

In [138]:
a = np.arange(0,4)
b = np.arange(4,8)
c = np.hstack((a,b))
d = np.concatenate((a,b))
e = np.vstack((a,b))
f = np.concatenate((a[newaxis,:],b[newaxis,:]))
print(f'{a=}\n{b=}\n{c=}\n{d=}\n{e=}\n{f=}')

a=array([0, 1, 2, 3])
b=array([4, 5, 6, 7])
c=array([0, 1, 2, 3, 4, 5, 6, 7])
d=array([0, 1, 2, 3, 4, 5, 6, 7])
e=array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
f=array([[0, 1, 2, 3],
       [4, 5, 6, 7]])


* `split(a, split_points, axis=0)`
   * `a` &rarr; the array to split
   *  `split_points`
      * $N$ (int) &rarr; array is divided into $N$ equal arrays (or fails)
      * integer seq &rarr; split indexes (points)
   * `axis` &rarr; the axis along which to split

<br>

In [153]:
a = np.arange(42).reshape((6,7))
upper,center,lower = np.split(a,3)
print(f'{a=}\n{upper=}\n{center=}\n{lower=}')

a=array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41]])
upper=array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])
center=array([[14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])
lower=array([[28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41]])


In [151]:
a = np.arange(42).reshape((6,7))
# ERROR: array split does not result in an equal division
#upper,lower = np.split(a,2,axis=1)

In [181]:
a = np.arange(36).reshape((6,6))
upper,center,lower = np.split(a,(1,3))
print(f'{a=}\n{upper=}\n{center=}\n{lower=}')

a=array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])
upper=array([[0, 1, 2, 3, 4, 5]])
center=array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])
lower=array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])


<br>

In [182]:
a = np.arange(0,14).reshape((2,7))
left,center,right = np.split(a,(1,3), axis=1)
print(f'{a=}\n{left=}\n{center=}\n{right=}')

a=array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])
left=array([[0],
       [7]])
center=array([[1, 2],
       [8, 9]])
right=array([[ 3,  4,  5,  6],
       [10, 11, 12, 13]])


* `vsplit` and `hsplit` - 2 (or more) dimensional arrays
    * `vsplit(a,ii)` == `split(a, ii, axis=0)`
    * `hsplit(a,ii)` == `split(a, ii, axis=1)`
* `hsplit` - 1 dimensional arrays
    * `hsplit(a,ii)` == `split(a, ii)`

<br>

In [183]:
a = np.arange(16).reshape((4,4))
b,c = np.vsplit(a,2)
d,e = np.split(a,2, axis=0)
print(f'{a=}\n{b=}\n{c=}\n{d=}\n{e=}')

a=array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])
b=array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
c=array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])
d=array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
e=array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])


In [174]:
a = np.arange(16).reshape((4,4))
b,c = np.hsplit(a,2)
d,e = np.split(a,2, axis=1)
print(f'{a=}\n{b=}\n{c=}\n{d=}\n{e=}')

a=array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])
b=array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])
c=array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])
d=array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])
e=array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])


In [175]:
a = np.arange(16)
b,c = np.hsplit(a,2)
d,e = np.split(a,2)
print(f'{a=}\n{b=}\n{c=}\n{d=}\n{e=}')

a=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
b=array([0, 1, 2, 3, 4, 5, 6, 7])
c=array([ 8,  9, 10, 11, 12, 13, 14, 15])
d=array([0, 1, 2, 3, 4, 5, 6, 7])
e=array([ 8,  9, 10, 11, 12, 13, 14, 15])


In [184]:
#help(np.vsplit)

## UFuncs - Universal Functions

## Aggregations Functions

## Broadcasting

## Boolean Manipulation

## Fancy Indexing